name: "Get & Cache Dependencies"
description: "Get the dependencies (via npm) and cache them"
runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install Dependencies
      id: install
      run: |
        npm ci
      shell: bash
